fgms-0:
    title: FlightGear Multiplayer Server (0.x Stable)
    runlevel: 0
    color: "#A684AC"
    version: 
        number: 0.x.stable
    repo: git
    checkout: git://gitorious.org/~ffs/fgms/ffss-fgms-0-x.git
    branch: master
    official: 0
    doxy_file: docx/doxy.conf

fgms-1:
    title: FlightGear Multiplayer Server (1.x Dev)
    runlevel: 0
    color: "#A684AC"
    version: 
        number: 1.x.dev
    repo: git
    checkout: git://gitorious.org/~ffs/fgms/ffs-docs-fgms-1-x
    official: 0
    doxy_file: docx/doxy.conf 

osg:
    title: OpenSceneGraph
    runlevel: 15
    color: "#5F89B3"
    version: 
        number: 1.8.5
    repo: svn
    checkout: http://www.openscenegraph.org/svn/osg/OpenSceneGraph/tags/OpenSceneGraph-3.1.1
    official: 1
    copy:
      - etc/DoxyMain-osg.cpp
    doxy_args:
       INPUT: DoxyMain-osg.cpp src/

plib:
    title: Steves's Portable Game Library
    runlevel: 10
    color: "#539053"
    version: 
        number: 1.8.5
    repo: svn
    checkout: https://plib.svn.sourceforge.net/svnroot/plib/trunk
    official: 1
    copy:
      - etc/DoxyMain-plib.cpp
    doxy_args:
       INPUT: DoxyMain-plib.cpp src/
       HTML_COLORSTYLE_HUE: 120
       HTML_COLORSTYLE_SAT: 80
       HTML_COLORSTYLE_GAMMA: 220

fg-docs:
    title: FlightGear Documentation Project
    runlevel: 100
    color: red
    version: 
        number: 0.1
    repo: git
    checkout: https://git.gitorious.org/~ffs/flightgear-docs-project
    official: 1
    copy:
      - etc/DoxyMain-fgdocs.cpp
      - py_update.py
    doxy_args:
       INPUT: DoxyMain-fgdocs.cpp py_update.py
       GENERATE_TREEVIEW: NO
       SHOW_NAMESPACES: NO
       EXAMPLE_PATH: ./

