terragear:
    abbrev: TerraGear
    title: TerraGear - Scenery Builder
    runlevel: 60
    color: "#9ECC9E"
    version: 
        number: git
    repo: git
    checkout: git://gitorious.org/fg/terragear.git
    project_page: https://gitorious.org/fg/terragear
    branch: master
    official: 0
    tags: simgear
    doxy_args:
        HTML_COLORSTYLE_HUE: 120
        HTML_COLORSTYLE_SAT: 80
        HTML_COLORSTYLE_GAMMA: 220

osg:
    abbrev: OSG
    title: OpenSceneGraph
    runlevel: 15
    color: "#5F89B3"
    version: 
        number: 3.2.1
    repo: svn
    checkout: http://www.openscenegraph.org/svn/osg/OpenSceneGraph/tags/OpenSceneGraph-3.2.1
    project_page: http://www.openscenegraph.org/
    branch: stable
    official: 1
    copy:
      - etc/DoxyMain-osg.cpp
    doxy_args:
       INPUT: DoxyMain-osg.cpp src/ include/ 
       FILE_PATTERNS: "*include* *.cpp"

       
plib:
    abbrev: PLIB
    title: Portable Game Library
    runlevel: 10
    color: "#539053"
    version: 
        number: 1.8.5
    repo: svn
    checkout: https://svn.code.sf.net/p/plib/code/trunk
    project_page: http://sourceforge.net/projects/plib/
    branch: stable
    official: 1
    copy:
      - etc/DoxyMain-plib.cpp
    doxy_args:
        INPUT: DoxyMain-plib.cpp src/
        EXAMPLE_PATH: ./
        HTML_COLORSTYLE_HUE: 120
        HTML_COLORSTYLE_SAT: 80
        HTML_COLORSTYLE_GAMMA: 220

simgear:
    abbrev: SimGear
    title: SimGear - Simulator Construction Tools
    runlevel: 50
    color: "#DEDE45"
    tags: osg plib
    version: 
        file: version
    repo: git
    checkout: git://gitorious.org/fg/simgear.git
    project_page: https://gitorious.org/fg/simgear
    branch: next
    official: 1
    doxy_args:
       INPUT: DoxygenMain.cxx simgear/
       HTML_COLORSTYLE_HUE: 60
       HTML_COLORSTYLE_SAT: 180
       HTML_COLORSTYLE_GAMMA: 220

flightgear:
    abbrev: FlightGear
    title: FlightGear - Flight Simulator
    runlevel: 80
    color: "#6280BA"
    tags: osg plib simgear
    version: 
        file: version
    repo: git
    checkout: git://gitorious.org/fg/flightgear.git
    project_page: https://gitorious.org/fg/flightgear
    branch: next
    official: 0
    copy: 
        - etc/DoxyMain-fg.cpp
    doxy_args:
        INPUT: DoxyMain-fg.cpp src/
        HTML_COLORSTYLE_HUE: 240
        HTML_COLORSTYLE_SAT: 40
        HTML_COLORSTYLE_GAMMA: 180
        HTML_EXTRA_FILES: docs-mini/* 

fgdocx:
    abbrev: fg-docs
    title: FlightGear API Docs
    runlevel: 100
    color: "#989898"
    version: 
        number: 0.2
    repo: git
    checkout: https://github.com/freeflightsim/flightgear-docs-project.git
    project_page: https://github.com/freeflightsim/flightgear-docs-project
    branch: master
    official: 1
    copy:
      - etc/DoxyMain-fgdocx.cpp
      - build_docs.py
      - etc/projects.config.yaml
      - etc/doxy-default.conf
      - fgdocx/
    doxy_args:
       INPUT: DoxyMain-fgdocx.cpp build_docs.py project_pages.cpp fgdocx/
       SHOW_NAMESPACES: YES
       EXAMPLE_PATH: ./
       OPTIMIZE_OUTPUT_JAVA: YES
       JAVADOC_AUTOBRIEF: YES
       HTML_COLORSTYLE_HUE: 200
       HTML_COLORSTYLE_SAT: 0
       HTML_COLORSTYLE_GAMMA: 240
       HIDE_SCOPE_NAMES: YES
       GENERATE_TREEVIEW: NO
       
